[package]
name = "hematite_ecs"
version = "0.1.0"
edition = "2021"

[lib]
name = "hematite_ecs"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"