[package]
name = "hematite"
version = "0.1.0"
edition = "2021"

[lib]
name = "hematite"
path = "src/lib.rs"

[[example]]
name = "simple"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
hematite_ecs = { path = "../hematite_ecs" }